# Generated by Django 5.2.14 on 2026-05-16 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('description', models.TextField(blank=True, default='')),
                ('university', models.CharField(max_length=120)),
                ('major', models.CharField(max_length=120)),
                ('academic_year', models.CharField(blank=True, default='', max_length=20)),
                ('project_type', models.CharField(choices=[('IMAGE', 'Image'), ('GITHUB', 'GitHub'), ('VIDEO', 'Video'), ('MIXED', 'Mixed')], default='MIXED', max_length=10)),
                ('github_url', models.URLField(blank=True, default='')),
                ('demo_url', models.URLField(blank=True, default='')),
                ('video_url', models.URLField(blank=True, default='')),
                ('cover_image', models.URLField(blank=True, default='')),
                ('gallery_images', models.JSONField(blank=True, default=list)),
                ('tech_stack', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('PUBLISHED', 'Published'), ('HIDDEN', 'Hidden'), ('REJECTED', 'Rejected')], default='PUBLISHED', max_length=12)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
