# Generated by Django 5.2.14 on 2026-06-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_promotioncampaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='proof_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='transfer_reference',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
